'use client';
import {useMemo,useRef,useState} from 'react';
import {AlertTriangle,ArrowRight,BarChart3,CheckCircle2,ChevronRight,ClipboardCheck,Download,FileCheck2,FileText,Home,Info,LayoutDashboard,RefreshCcw,ShieldCheck,Upload,Users,WalletCards,XCircle} from 'lucide-react';
import type {CaseResult} from '@/lib/underwriting';
import {markdownReport} from '@/lib/underwriting';

type Scenario='missing'|'corrected'|'high';
const scenarios:{id:Scenario;name:string;desc:string;file:string}[]=[
 {id:'missing',name:'Missing Evidence',desc:'Salary conflict + unsourced $20k deposit',file:'01_missing_evidence (2).zip'},
 {id:'corrected',name:'Corrected File',desc:'Matched transfer + corrected salary + W-2',file:'02_corrected.zip'},
 {id:'high',name:'High DTI',desc:'47% DTI manual-path escalation',file:'03_high_dti.zip'}
];
const money=(n:number)=>`$${Math.round(n).toLocaleString('en-US')}`;
function demoResult(s:Scenario):CaseResult{
 const income=10000, housing=2800, auto=s==='high'?1800:400, card=100, obligations=housing+auto+card, dti=obligations/income, loan=320000,purchase=400000,appraisal=410000,cash=92000,assets=s==='missing'?75000:95000;
 const findings:any[]=[];
 if(s==='missing'){findings.push({id:'INC-001',category:'Income',severity:'high',title:'Application income conflicts with supported payroll',detail:'Application salary is $132,000 while paystub and employment evidence support $120,000.',action:'Resolve the discrepancy and use the supported income figure for the test calculation.',evidence:['01_application.txt','02_paystub.txt','03_paystub.txt']},{id:'INC-002',category:'Income',severity:'medium',title:'2025 W-2 evidence is missing',detail:'The missing-evidence package does not contain the expected W-2 summary.',action:'Obtain the missing W-2 or permitted alternative.',evidence:['02_paystub.txt','04_employment_letter.txt']},{id:'AST-001',category:'Assets',severity:'high',title:'$20,000 deposit source is not identified',detail:'September checking shows a $20,000 incoming transfer without a source.',action:'Document the source and exclude the unsourced amount from verified funds.',evidence:['06_checking_september.txt']});}
 if(s==='corrected'){findings.push({id:'AST-002',category:'Assets',severity:'info',title:'$20,000 transfer is matched',detail:'Checking and savings statements identify the same own-account transfer; it is not double-counted.',action:'Retain the matching statements.',evidence:['06_checking_september.txt','13_savings_statements.txt']});}
 if(s==='high'){findings.push({id:'DTI-001',category:'Capacity',severity:'critical',title:'Manual-path DTI escalation at 47.0%',detail:'$4,700 monthly obligations divided by $10,000 supported income equals 47.0%.',action:'Escalate for human manual-underwriting review.',evidence:['07_credit_report_summary.txt','10_housing_and_cost_worksheet.txt']});}
 return {status:s==='high'?'ESCALATE FOR HUMAN REVIEW':s==='missing'?'CONDITIONAL REVIEW':'READY FOR HUMAN REVIEW',metrics:{income,obligations,housing,dti,loan,purchase,appraisal,ltvPurchase:.8,ltvAppraisal:loan/appraisal,cashRequired:cash,verifiedAssets:assets,assetGap:Math.max(0,cash-assets)},borrower:'Maya Sample',property:'TEST-HOUSE-001',program:'FNMA_MANUAL_FIXED_PURCHASE_1UNIT_PRIMARY_MVP',findings,documents:[],evidenceScore:s==='missing'?64:96,policyScore:s==='high'?82:94,summary:s==='high'?'The file requires human escalation because the calculated DTI is 47.0%.':s==='missing'?'The file is conditionally reviewable but has unresolved income and asset evidence issues.':'The synthetic evidence is internally consistent for this test case; human review is still required.',nextSteps:findings.filter(f=>f.severity!=='info').map(f=>f.action),sources:['Project-scoped FNMA MVP test guide','Synthetic borrower evidence package']};
}

export default function HomePage(){
 const input=useRef<HTMLInputElement>(null); const [files,setFiles]=useState<File[]>([]); const [scenario,setScenario]=useState<Scenario>('missing'); const [result,setResult]=useState<CaseResult|null>(null); const [loading,setLoading]=useState(false); const [error,setError]=useState(''); const [active,setActive]=useState('overview');
 const run=async()=>{setError('');setLoading(true);setResult(null);try{if(files.length){const fd=new FormData();files.forEach(f=>fd.append('files',f));const r=await fetch('/api/analyze',{method:'POST',body:fd});const j=await r.json();if(!r.ok)throw new Error(j.error);setResult(j.result);}else{await new Promise(r=>setTimeout(r,450));setResult(demoResult(scenario));}setActive('overview')}catch(e){setError(e instanceof Error?e.message:'Analysis failed.')}finally{setLoading(false)}};
 const currentScenario=scenarios.find(s=>s.id===scenario)!;
 const nav=[['overview','Overview',LayoutDashboard],['documents','Evidence',FileCheck2],['findings','Findings',AlertTriangle],['calculations','Calculations',BarChart3],['policy','Policy',ShieldCheck],['report','Report',FileText]] as const;
 const download=(format:'md'|'json'='md')=>{if(!result)return;const body=format==='json'?JSON.stringify(result,null,2):markdownReport(result);const blob=new Blob([body],{type:format==='json'?'application/json':'text/markdown'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`underwriting-review-v2.${format}`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
 const counts=useMemo(()=>result?{critical:result.findings.filter(f=>f.severity==='critical').length,high:result.findings.filter(f=>f.severity==='high').length,medium:result.findings.filter(f=>f.severity==='medium').length}:null,[result]);
 return <div className="app-shell">
  <aside className="sidebar"><div className="brand"><div className="brand-mark"><Home size={19}/></div><div><strong>UnderwriteAI</strong><span>Mortgage Workbench</span></div></div><div className="side-label">WORKSPACE</div>{nav.map(([id,label,Icon])=><button key={id} data-nav={id} className={`nav-item ${active===id?'active':''}`} onClick={()=>setActive(id)}><Icon size={17}/><span>{label}</span>{id==='findings'&&counts&&counts.critical+counts.high>0?<b>{counts.critical+counts.high}</b>:<ChevronRight size={14} className="nav-arrow"/>}</button>)}<div className="side-spacer"/><div className="human-note"><ShieldCheck size={18}/><div><strong>Human-in-the-loop</strong><span>Decision support only. No automatic loan approval or denial.</span></div></div><div className="version">V2.0 • Demo environment</div></aside>
  <main className="main"><header className="topbar"><div><div className="eyebrow">UNDERWRITING WORKSPACE</div><h1>Mortgage file review</h1></div><div className="top-actions"><span className="program-pill">FNMA Manual MVP</span><button className="ghost" onClick={()=>{setResult(null);setFiles([]);setError('');if(input.current) input.current.value=''}}><RefreshCcw size={15}/> New review</button></div></header>
  {!result?<section className="intake"><div className="hero-card"><div><div className="eyebrow">AI-ASSISTED • EVIDENCE-FIRST</div><h2>Turn a borrower package into a review-ready file.</h2><p>Upload your test package or run one of the built-in synthetic scenarios. Calculations are deterministic; AI is optional.</p></div><div className="hero-orb"><ClipboardCheck size={34}/></div></div>
   <div className="grid-2"><div className="panel"><div className="panel-head"><div><h3>1. Choose a test case</h3><p>These mirror the supplied synthetic FNMA test fixtures.</p></div><span className="step">01</span></div>{scenarios.map(s=><button key={s.id} className={`scenario ${scenario===s.id?'selected':''}`} onClick={()=>setScenario(s.id)}><div className="scenario-icon"><FileText size={17}/></div><div className="scenario-copy"><strong>{s.name}</strong><span>{s.desc}</span></div><div className="radio">{scenario===s.id&&<i/>}</div></button>)}</div>
   <div className="panel"><div className="panel-head"><div><h3>2. Upload borrower package</h3><p>TXT, PDF, DOCX or ZIP. ZIP works best for the supplied fixtures.</p></div><span className="step">02</span></div><button className="dropzone" onClick={()=>input.current?.click()}><div className="upload-icon"><Upload size={20}/></div><strong>{files.length?'Add / replace files':'Drop documents here'}</strong><span>or click to browse • up to 180k characters</span></button><input ref={input} hidden type="file" multiple accept=".txt,.pdf,.docx,.zip,.md,.csv" onChange={e=>setFiles(Array.from(e.target.files||[]))}/>{files.length>0&&<div className="file-list">{files.map(f=><div className="file-row" key={f.name}><FileText size={15}/><span>{f.name}</span><button onClick={()=>setFiles(files.filter(x=>x!==f))}><XCircle size={15}/></button></div>)}</div>}<div className="upload-hint"><Info size={14}/> Uploaded files take precedence over the demo scenario. No files runs the selected fixture.</div></div></div>
   <div className="run-bar"><div><strong>{files.length?`${files.length} file${files.length>1?'s':''} ready for analysis`:currentScenario.name}</strong><span>{files.length?'Real uploaded evidence will be parsed on the server.':'Synthetic regression fixture will run without an API key.'}</span></div><button className="primary" onClick={run} disabled={loading}>{loading?'Analyzing…':<>Run underwriting review <ArrowRight size={17}/></>}</button></div>
   {error&&<div className="error-box"><AlertTriangle size={17}/>{error}</div>}
   <div className="architecture"><div><span>PIPELINE</span><strong>Documents → Evidence → Calculations → Findings → Human review</strong></div><div className="arch-agents"><span>Deterministic engine</span><span>Policy layer</span><span>Optional Groq AI</span></div></div>
  </section>:<section className="workspace">
   <div className="status-banner"><div className={`status-dot ${result.status.startsWith('ESCALATE')?'critical':result.status.startsWith('CONDITIONAL')?'warning':'good'}`}></div><div><strong>{result.status}</strong><span>{result.summary}</span></div><div className="report-actions"><button className="secondary small" onClick={()=>download('json')}><Download size={15}/> JSON</button><button className="primary small" onClick={()=>download('md')}><Download size={15}/> Markdown</button></div></div>
   {active==='overview'&&<Overview r={result} counts={counts!}/>} {active==='documents'&&<Documents r={result}/>} {active==='findings'&&<Findings r={result}/>} {active==='calculations'&&<Calculations r={result}/>} {active==='policy'&&<Policy r={result}/>} {active==='report'&&<Report r={result} onDownload={download}/>} 
  </section>}
  </main>
 </div>
}
function Metric({label,value,sub,tone}:{label:string;value:string;sub:string;tone?:string}){return <div className="metric"><span>{label}</span><strong className={tone||''}>{value}</strong><small>{sub}</small></div>}
function Overview({r,counts}:{r:CaseResult;counts:any}){return <div className="content"><div className="metrics"><Metric label="Supported income" value={money(r.metrics.income)} sub="monthly"/><Metric label="DTI" value={r.metrics.dti?(r.metrics.dti*100).toFixed(1)+'%':'—'} sub="deterministic calculation" tone={r.metrics.dti&&r.metrics.dti>=.45?'danger':''}/><Metric label="Purchase LTV" value={r.metrics.ltvPurchase?(r.metrics.ltvPurchase*100).toFixed(1)+'%':'—'} sub="loan ÷ purchase price"/><Metric label="Verified assets" value={money(r.metrics.verifiedAssets)} sub={r.metrics.assetGap?`${money(r.metrics.assetGap)} gap`:'cash requirement covered'}/></div><div className="two-col"><div className="panel"><div className="panel-head"><div><h3>File health</h3><p>Signals across evidence and policy review.</p></div><CheckCircle2 size={20} className="muted"/></div><div className="health"><div><span>Evidence signal</span><b>{r.evidenceScore}%</b></div><div className="progress"><i style={{width:`${r.evidenceScore}%`}}/></div><div><span>Policy review signal</span><b>{r.policyScore}%</b></div><div className="progress"><i style={{width:`${r.policyScore}%`}}/></div></div><div className="legend"><span><i className="dot red"/> {counts.critical} critical</span><span><i className="dot amber"/> {counts.high} high</span><span><i className="dot gray"/> {counts.medium} medium</span></div></div><div className="panel"><div className="panel-head"><div><h3>Borrower snapshot</h3><p>Parsed from the supplied package.</p></div><Users size={19} className="muted"/></div><div className="snapshot"><div><span>Borrower</span><strong>{r.borrower}</strong></div><div><span>Property</span><strong>{r.property}</strong></div><div><span>Loan</span><strong>{money(r.metrics.loan)}</strong></div><div><span>Purchase</span><strong>{money(r.metrics.purchase)}</strong></div><div><span>Appraisal</span><strong>{money(r.metrics.appraisal)}</strong></div><div><span>Housing</span><strong>{money(r.metrics.housing)}/mo</strong></div></div></div></div><div className="panel"><div className="panel-head"><div><h3>Priority findings</h3><p>Start here before reading the full report.</p></div><button className="linkish" onClick={()=>document.querySelector<HTMLButtonElement>('[data-nav=findings]')?.click()}>View all <ArrowRight size={14}/></button></div><div className="finding-list">{r.findings.slice(0,4).map(f=><FindingRow key={f.id} f={f}/>)}</div></div></div>}
function FindingRow({f}:any){return <div className="finding-row"><div className={`severity ${f.severity}`}>{f.severity==='critical'?<XCircle size={15}/>:f.severity==='info'?<Info size={15}/>:<AlertTriangle size={15}/>}</div><div className="finding-body"><div><span className="finding-id">{f.id}</span><strong>{f.title}</strong></div><p>{f.detail}</p><span className="action">Next: {f.action}</span></div></div>}
function Documents({r}:{r:CaseResult}){return <div className="content"><div className="section-title"><div><div className="eyebrow">EVIDENCE</div><h2>Document inventory</h2><p>Every uploaded source is kept visible so conclusions can be traced back to evidence.</p></div></div><div className="panel table"><div className="table-head"><span>Document</span><span>Type</span><span>Status</span></div>{r.documents.length?r.documents.map(d=><div className="table-row" key={d.name}><span><FileText size={15}/>{d.name}</span><span>{d.kind}</span><span className="badge good">Parsed</span></div>):<div className="empty"><FileCheck2 size={22}/><strong>Synthetic scenario loaded</strong><span>Upload a package to see its individual document inventory.</span></div>}</div></div>}
function Findings({r}:{r:CaseResult}){return <div className="content"><div className="section-title"><div><div className="eyebrow">FINDINGS</div><h2>Conditions & conflicts</h2><p>Structured findings replace long unstructured agent paragraphs.</p></div></div><div className="finding-list panel">{r.findings.map(f=><FindingRow key={f.id} f={f}/>)}</div></div>}
function Calculations({r}:{r:CaseResult}){const m=r.metrics;return <div className="content"><div className="section-title"><div><div className="eyebrow">DETERMINISTIC ENGINE</div><h2>Financial calculations</h2><p>Arithmetic is performed by code, not by the language model.</p></div></div><div className="calc-grid"><div className="calc-card"><span>Monthly income</span><strong>{money(m.income)}</strong><small>Supported base salary ÷ 12</small></div><div className="calc-card"><span>Monthly obligations</span><strong>{money(m.obligations)}</strong><small>Housing + recurring debts</small></div><div className="calc-card highlight"><span>Debt-to-income</span><strong>{m.dti?(m.dti*100).toFixed(1)+'%':'—'}</strong><small>{m.dti&&m.dti>=.45?'Escalation signal':'Calculated from supported values'}</small></div><div className="calc-card"><span>Purchase LTV</span><strong>{m.ltvPurchase?(m.ltvPurchase*100).toFixed(1)+'%':'—'}</strong><small>{money(m.loan)} ÷ {money(m.purchase)}</small></div><div className="calc-card"><span>Appraisal LTV</span><strong>{m.ltvAppraisal?(m.ltvAppraisal*100).toFixed(1)+'%':'—'}</strong><small>{money(m.loan)} ÷ {money(m.appraisal)}</small></div><div className="calc-card"><span>Cash position</span><strong>{money(m.verifiedAssets)}</strong><small>{m.assetGap?money(m.assetGap)+' below required':'covers estimated cash required'}</small></div></div></div>}
function Policy({r}:{r:CaseResult}){return <div className="content"><div className="section-title"><div><div className="eyebrow">POLICY LAYER</div><h2>Scoped policy review</h2><p>Scoped to the supplied synthetic FNMA MVP corpus; this is a review aid, not a complete eligibility engine.</p></div><div className="policy-score"><ShieldCheck size={17}/><strong>{r.policyScore}%</strong><span>scoped signal</span></div></div><div className="policy-grid"><div className="panel"><h3>Program</h3><p>{r.program}</p><div className="policy-note"><Info size={16}/><span>Policy claims must be supported by the configured source corpus. Current fixtures are synthetic and require human validation.</span></div></div><div className="panel"><h3>Review boundaries</h3><ul><li>No automatic approval or denial</li><li>No lender overlay invention</li><li>No complete matrix eligibility determination</li><li>No guarantee of document authenticity</li></ul></div></div></div>}
function Report({r,onDownload}:{r:CaseResult;onDownload:(format:'md'|'json')=>void}){return <div className="content"><div className="section-title"><div><div className="eyebrow">EXPORT</div><h2>Underwriting report</h2><p>A concise, traceable report for human review.</p></div><div className="report-actions"><button className="secondary small" onClick={()=>onDownload('json')}><Download size={15}/> JSON</button><button className="primary small" onClick={()=>onDownload('md')}><Download size={15}/> Markdown</button></div></div><div className="report panel"><h1>UnderwriteAI V2 Review</h1><div className="report-status">{r.status}</div><p>{r.summary}</p><h3>Metrics</h3><div className="report-metrics"><span>Income <b>{money(r.metrics.income)}</b></span><span>DTI <b>{r.metrics.dti?(r.metrics.dti*100).toFixed(1)+'%':'—'}</b></span><span>LTV <b>{r.metrics.ltvPurchase?(r.metrics.ltvPurchase*100).toFixed(1)+'%':'—'}</b></span><span>Assets <b>{money(r.metrics.verifiedAssets)}</b></span></div><h3>Findings</h3>{r.findings.map(f=><div className="report-finding" key={f.id}><strong>{f.id} — {f.title}</strong><p>{f.detail}</p><b>Action:</b> {f.action}</div>)}</div></div>}
